# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: ./.github/actions/checkout # Reference local version of checkout action

      - name: Set up Go
        uses: ./.github/actions/setup-go # Reference local version of setup-go action
        with:
          go-version: '1.20'

      - name: Install dependencies
        run: go mod tidy

      - name: Build the project
        run: go build -v ./...

      - name: Run tests
        run: go test -v ./...
