name: Build EXE

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: |
        mkdir -p build
        go build -o build/image-compare-tool.exe ./cmd

    - name: Test
      run: go test -v ./...

    - name: Archive build folder
      run: |
        Compress-Archive -Path build\* -DestinationPath image-compare.zip

    - name: Upload build artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: ./image-compare.zip